apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: fox
spec:
  promotionFlows:
    - name: prom-flow-tes
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - sdvsdv
    - name: prom-flow-tes
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '[production]'
        - key: gitRevision
          operator: In
          values:
            - production
  promotionTemplate:
    versionSource:
      file: values.yaml
      jsonPath: $.image.tag
    promotion:
      values.yaml:
        jsonPaths:
          - $.image.tag
