apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: guestbooks
spec:
  promotionTemplate:
    versionSource:
      file: not-exist-file.yaml
      jsonPath: $.replicaCount
    promotion:
      not-exist-file.yaml:
        jsonPaths:
          - $.replicaCount
  concurrency: queue
