apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: test-version
spec:
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.image.tag
    promotion:
      values-production.yaml:
        jsonPaths:
          - $.service.type
