apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: test
spec:
  promotionFlows:
    - name: prom-flow-tes
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - commit
  promotionTemplate:
    versionSource:
      file: values.yaml
      jsonPath: $.image.tag
      