apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: test-2
spec:
  promotionTemplate:
    versionSource:
      file: not-exist-file.yaml
      jsonPath: $.replicaCount
    promotion:
      not-exist-file.yaml:
        jsonPaths:
          - $.replicaCount
      values-production.yaml:
        jsonPaths:
          - $.*.type
  concurrency: queue
