gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
  global:
    codefresh:
      accountId: 65f80465351a7afd2247a100
      url: https://plakyda-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - growth-team.rnd-sandbox.cf-infra.com
        protocol: https
      name: golf5
  installer:
    skipValidation: true
