apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  labels:
    codefresh.io/entity: runtime
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/app-group: alpha
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/plakyda-codefresh/argocd-example-apps
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: guestbook
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false