apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: sdvsdvsdvsdv
  annotations:
    description: svsdv1sc
spec:
  triggerEnvironment: test
  steps:
    - environment: prod
      dependsOn:
        - test
      policy:
        action: commit
    - environment: test23
      dependsOn:
        - prod
      policy:
        action: commit
