apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: temp3
  annotations:
    description: ""
spec:
  triggerEnvironment: prod
  steps:
    - environment: qa
      dependsOn:
        - prod
      policy:
        action: commit
