gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
  global:
    codefresh:
      accountId: 67fd91f7fc62c16e6a387bf5
      url: http://host.docker.internal
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        enabled: false
      # ingressUrl: http://local.codefresh.io:8080
      ingressUrl: http://plakyda-ingresshost.ngrok.io
      name: golf56
      isConfigurationRuntime: true
  installer:
    skipValidation: false
  internal-router:
    service:
      nodePort: 31243
      type: NodePort
  tunnel-client:
    enabled: false
