gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
    image:
      tag: 1.3328.0
    initContainer:
      image:
        tag: 1.3328.0
  global:
    codefresh:
      accountId: 67dd5d91eaf0168b149b63a4
      url: https://plakyda-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - growth-team.rnd-sandbox.cf-infra.com
        protocol: https
      name: golf12
  installer:
    skipValidation: true
