apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: fox
spec:
  promotionFlows:
    - name: prom-flow-tes
      triggerConditions:
        - property: commitMessage
          operator: In
          value: sdvsdvs
