apiVersion: codefresh.io/v1beta1
kind: PromotionPolicy
metadata:
  name: test
spec:
  priority: 1
  selector:
    product:
      names:
        - super
        - jupiter-new
  policy:
    action: commit
    preAction: prom-workflow
