apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runtime-app
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/plakyda-codefresh/runtimes.git
    targetRevision: HEAD
    path: resources/golf49/chart
    helm:
      releaseName: golf49-release
  destination:
    namespace: gitops-runtime
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
