gitops-runtime:
  argo-cd:
    acrController:
      enabled: true
    eventReporter:
      enabled: 'true'
      version: v2
      env:
        - name: USE_GRPC
          value: 'true'
    repoServer:
      replicas: 1
    controller:
      replicas: 1
    server:
      replicas: 1
      service:
        type: LoadBalancer
  app-proxy:
    config:
      cors: http://local.codefresh.io
  global:
    codefresh:
      accountId: 65f80465351a7afd2247a100
      url: https://plakyda-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - deadpool.rnd-sandbox.cf-infra.com
        protocol: https
      name: deadpool
      isConfigurationRuntime: true
  installer:
    skipValidation: true
