gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io
    env:
      HELM_REPOSITORY: oci://quay.io/codefresh/dev/gitops-runtime
  argo-workflows:
    controller:
      workflowDefaults:
        spec:
          archiveLogs: true
          artifactRepositoryRef:
            configMap: codefresh-workflows-log-store
            key: codefresh-workflows-log-store
  global:
    codefresh:
      accountId: 67fd91f7fc62c16e6a387bf5
      url: https://plakyda-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingressUrl: http://local.codefresh.io:8080
      ingress:
        enabled: false
      name: golf34
      isConfigurationRuntime: true
  installer:
    skipValidation: true
  tunnel-client:
    enabled: false # important!
  internal-router:
    service:
      type: NodePort # important!
      nodePort: 31243
