gitops-runtime:
  argo-cd:
    eventReporter:
      enabled: "true"
      version: v2
      env: 
        - name: USE_GRPC
          value: "true"
    repoServer:
      replicas: 1
    controller:
      replicas: 1
    server:
      replicas: 1
        # image:
        # repository: docker.io/xeonalex/personal-argocd-dev
      # tag: 2.8.1-parrallel-events-23
      service:
        # annotations:
        #   kubernetes.io/ingress.class: nginx-public
        type: LoadBalancer
  app-proxy:
    config:
      cors: http://local.codefresh.io
  global:
    codefresh:
      accountId: 65f80465351a7afd2247a100
      url: https://plakyda-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - hermes-victor.rnd-sandbox.cf-infra.com
        protocol: https
      name: mustang
  installer:
    skipValidation: true
