# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: prom-workflow
  annotations:
    version: 0.0.1
    codefresh.io/workflow-origin: promotion
spec:
  arguments:
    parameters:
      - name: APP_NAME
      - name: COMMIT_SHA
      - name: COMMIT_AUTHOR
      - name: COMMIT_MESSAGE
      - name: COMMIT_DATE
      - name: ARGOCD_HOST
  entrypoint: echo
  templates:
    - name: echo
      script:
        image: alpine
        command:
          - sh
        source: >
          echo "syncing {{ workflow.parameters.APP_NAME }} to {{
          workflow.parameters.COMMIT_SHA }}, author: {{
          workflow.parameters.COMMIT_AUTHOR }}, commit message: {{
          workflow.parameters.COMMIT_MESSAGE }}, commit date: {{
          workflow.parameters.COMMIT_DATE }}, argo cd host: {{
          workflow.parameters.ARGOCD_HOST }}"
