apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: golf7
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,control-planes/**/*.yaml,control-planes/*.yaml,golf7/cf-gitops-runtime.yaml,golf7/empty.yaml,runtimes/golf7/**/*.yaml,runtimes/golf7/*.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/plakyda-codefresh/runtimes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
